//
//  BorderedCellBackgroundView.h
//  iLinX
//
//  Created by mcf on 05/05/2010.
//  Copyright 2010 Micropraxis Ltd. All rights reserved.
//

#import <UIKit/UIKit.h>

#define BORDER_LINE_SEPARATOR 0x01
#define BORDER_LINE_SECTION_SIDES 0x02
#define BORDER_LINE_SECTION_TOP 0x04
#define BORDER_LINE_SECTION_BOTTOM 0x08

#define BORDER_TYPE_NONE            0
#define BORDER_TYPE_SEPARATOR_ONLY  BORDER_LINE_SEPARATOR  
#define BORDER_TYPE_MIDDLE_NO_SEP   BORDER_LINE_SECTION_SIDES
#define BORDER_TYPE_MIDDLE          (BORDER_LINE_SEPARATOR|BORDER_LINE_SECTION_SIDES)
#define BORDER_TYPE_TOP_NO_SEP      (BORDER_LINE_SECTION_SIDES|BORDER_LINE_SECTION_TOP)
#define BORDER_TYPE_TOP             (BORDER_LINE_SEPARATOR|BORDER_LINE_SECTION_SIDES|BORDER_LINE_SECTION_TOP)
#define BORDER_TYPE_BOTTOM_NO_SEP   (BORDER_LINE_SECTION_SIDES|BORDER_LINE_SECTION_BOTTOM)
#define BORDER_TYPE_BOTTOM          (BORDER_LINE_SEPARATOR|BORDER_LINE_SECTION_SIDES|BORDER_LINE_SECTION_BOTTOM)
#define BORDER_TYPE_SINGLE_NO_SEP   (BORDER_LINE_SECTION_SIDES|BORDER_LINE_SECTION_TOP|BORDER_LINE_SECTION_BOTTOM)
#define BORDER_TYPE_SINGLE          (BORDER_LINE_SEPARATOR|BORDER_LINE_SECTION_SIDES|BORDER_LINE_SECTION_TOP|BORDER_LINE_SECTION_BOTTOM)

@interface BorderedCellBackgroundView : UIView 
{
@private
  UIColor *_fillColour;
  UIColor *_borderColour;
  NSInteger _borderType;
}

@property (nonatomic, retain) UIColor *fillColour;
@property (nonatomic, retain) UIColor *borderColour;
@property (assign) NSInteger borderType;

@end
